apiVersion: v1
kind: ConfigMap
metadata:
  name: my-website-config
  namespace: student-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>GitOps Demo</title></head>
    <body style="background-color: #2d3436; color: white; text-align: center; padding-top: 50px;">
      <h1>Hello Class 1125!</h1>
      <p>Deployed via ArgoCD</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student-apps
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: student-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          volumeMounts:
            - name: website-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: website-config
          configMap:
            name: my-website-config
            items:
              - key: index.html
                path: index.html